# BIXI Montreal
There is four CSV file, one for each ear (2014 - 2017)

In [6]:
import pandas as pd
import matplotlib.pyplot as plt

# set up the figure size
%matplotlib inline

# preview of each file
def preview_data(data):
    bold = '\033[1m'
    unbold = '\033[0m'
    print(bold + "The dimension of the table is:" + unbold, data.shape)
    print(bold + "\n\nFirst 5 rows preview:\n" + unbold, data.head())
    print(bold + "\n\nThe describtion of numerical columns is:\n" + unbold, data.describe())
    print(bold + "\nAnd the describtion of categorial columns is:\n" + unbold, data.describe(include=['O']))

## BIXI dataset

# BIXI_2015 = pd.read_csv('~/Downloads/biximtl/OD_2015.csv')
# preview_data(BIXI_2015)

# NYC Turnstile usage data
There is two csv files (2017 & 2018)

In [28]:
subway_2017 = pd.read_csv('~/Downloads/nys-turnstile-usage-data/turnstile-usage-data-2017.csv')

preview_data(subway_2017)

The dimension of the table is: (8878203, 11)


First 5 rows preview:
     C/A  Unit       SCP         Station Line Name Division  \
0  R629  R065  00-00-01     ROCKAWAY AV         3      IRT
1  N317  R267  02-06-00           46 ST        MR      IND
2  B025  R150  00-00-00        AVENUE U        BQ      BMT
3  A061  R142  00-00-00  DELANCEY/ESSEX      FJMZ      BMT
4  R257  R182  01-03-00          116 ST         6      IRT

                      Date      Time Description   Entries  \
0  2017-01-06T00:00:00.000  15:00:00     REGULAR   5723234
1  2017-01-04T00:00:00.000  16:00:00     REGULAR    281688
2  2017-01-01T00:00:00.000  20:00:00     REGULAR   4052069
3  2017-01-01T00:00:00.000  16:00:00     REGULAR  10956480
4  2017-01-02T00:00:00.000  00:00:00     REGULAR   8620297

   Exits
0                                            5956815
1                                             388139
2                                            2654916
3                                           10663406
4                                            9569207


The describtion of numerical columns is:
             Entries  \
count  8.878203e+06
mean   3.829531e+07
std    2.037046e+08
min    0.000000e+00
25%    5.061090e+05
50%    2.659916e+06
75%    6.814634e+06
max    2.130669e+09

       Exits
count                                       8.878203e+06
mean                                        3.071709e+07
std                                         1.842514e+08
min                                         0.000000e+00
25%                                         2.508190e+05
50%                                         1.491007e+06
75%                                         4.770183e+06
max                                         2.140537e+09

And the describtion of categorial columns is:
             C/A     Unit       SCP         Station Line Name Division  \
count   8878203  8878203   8878203         8878203   8878203  8878203
unique      737      470       237             380       114        6
top       PTH22     R549  00-00-00  34 ST-PENN STA         1      IRT
freq      65008   125949    872648          188255   1050035  3231017

                           Date      Time Description
count                   8878203   8878203     8878203
unique                      315     84923           2
top     2017-04-12T00:00:00.000  04:00:00     REGULAR
freq                      31452    687627     8845081

# NYC restaurant inspection

In [5]:
inspection_data = pd.read_csv('~/Downloads/nyc-inspection/DOHMH_New_York_City_Restaurant_Inspection_Results.csv')

preview_data(inspection_data)

The dimension of the table is: (399918, 18)


First 5 rows preview:
       CAMIS                      DBA           BORO BUILDING         STREET  \
0  40511702        NOTARO RESTAURANT      MANHATTAN      635  SECOND AVENUE
1  40511702        NOTARO RESTAURANT      MANHATTAN      635  SECOND AVENUE
2  50046354                 VITE BAR         QUEENS     2507       BROADWAY
3  50061389  TACK'S CHINESE TAKE OUT  STATEN ISLAND      11C    HOLDEN BLVD
4  41516263               NO QUARTER       BROOKLYN     8015       5 AVENUE

   ZIPCODE       PHONE CUISINE DESCRIPTION INSPECTION DATE  \
0  10016.0  2126863400             Italian      06/15/2015
1  10016.0  2126863400             Italian      11/25/2014
2  11106.0  3478134702             Italian      10/03/2016
3  10314.0  7189839854             Chinese      05/17/2017
4  11209.0  7187019180            American      03/30/2017

                                            ACTION VIOLATION CODE  \
0  Violations were cited in the following area(s).            02B
1  Violations were cited in the following area(s).            20F
2  Violations were cited in the following area(s).            10F
3  Violations were cited in the following area(s).            02G
4  Violations were cited in the following area(s).            04M

                               VIOLATION DESCRIPTION CRITICAL FLAG  SCORE  \
0        Hot food item not held at or above 140Âº F.      Critical   30.0
1              Current letter grade card not posted.  Not Critical    NaN
2  Non-food contact surface improperly constructe...  Not Critical    2.0
3  Cold food item held above 41Âº F (smoked fish ...      Critical   46.0
4  Live roaches present in facility's food and/or...      Critical   18.0

  GRADE GRADE DATE RECORD DATE  \
0   NaN        NaN  08/28/2017
1   NaN        NaN  08/28/2017
2   NaN        NaN  08/28/2017
3   NaN        NaN  08/28/2017
4   NaN        NaN  08/28/2017

                                     INSPECTION TYPE
0              Cycle Inspection / Initial Inspection
1  Administrative Miscellaneous / Initial Inspection
2      Pre-permit (Operational) / Initial Inspection
3      Pre-permit (Operational) / Initial Inspection
4              Cycle Inspection / Initial Inspection


The describtion of numerical columns is:
               CAMIS        ZIPCODE          SCORE
count  3.999180e+05  399909.000000  376704.000000
mean   4.441662e+07   10673.386933      18.910181
std    4.245117e+06     598.959356      12.958955
min    3.007544e+07   10001.000000      -2.000000
25%    4.121603e+07   10022.000000      11.000000
50%    4.160911e+07   10467.000000      15.000000
75%    5.000934e+07   11229.000000      24.000000
max    5.006908e+07   11697.000000     151.000000

And the describtion of categorial columns is:
                    DBA       BORO BUILDING    STREET       PHONE  \
count           399559     399918   399809    399909      399913
unique           20936          6     7256      3328       25165
top     DUNKIN' DONUTS  MANHATTAN        0  BROADWAY  7186566210
freq              4296     159574     2372     14791         240

       CUISINE DESCRIPTION INSPECTION DATE  \
count               399918          399918
unique                  84            1414
top               American      01/01/1900
freq                 90968            1135

                                                 ACTION VIOLATION CODE  \
count                                            398783         393414
unique                                                5             97
top     Violations were cited in the following area(s).            10F
freq                                             380632          55785

                                    VIOLATION DESCRIPTION CRITICAL FLAG  \
count                                              392939        399918
unique                                                 93             3
top     Non-food contact surface improperly constructe...      Critical
freq                                                55785        220082

         GRADE  GRADE DATE RECORD DATE                        INSPECTION TYPE
count   195413      192820      399918                                 398783
unique       6        1325           1                                     34
top          A  08/24/2016  08/28/2017  Cycle Inspection / Initial Inspection
freq    154194         455      399918                                 230431

# Austin, Texas scooter-sharing

In [30]:
scooter_data = pd.read_csv('~/Downloads/Dockless_Vehicle_Trips.csv')

preview_data(scooter_data)

The dimension of the table is: (4414975, 16)


First 5 rows preview:
                                      ID                             Device ID  \
0  6865731e-5e4b-4819-9435-4e62e09a652d  08c8c852-257c-49ad-a14f-727bfc79626d
1  08dc0d9c-735e-4006-b9af-60011509e469  255716b5-4a9f-4efc-9967-7a65b3521bac
2  9643609b-f548-4ccc-b96c-cc625a34a6c1  a8813574-e5fe-4ce3-ac18-924ddedd1c7e
3  da2f4ebd-bdd7-48ee-bc6a-bf94a5798b33  6bf00459-0fce-4b7b-943d-ff169220f90b
4  326432d7-b32e-4cd7-94ac-9b1062312421  6847fb45-771a-435c-acaa-05ecf1a2bee8

  Vehicle Type  Trip Duration  Trip Distance              Start Time  \
0          NaN            NaN            NaN                     NaN
1      bicycle     11491603.0         1658.0  11/30/2018 11:00:00 AM
2      scooter           46.0            0.0  10/07/2018 12:45:00 AM
3      scooter          181.0            0.0  02/17/2019 12:45:00 AM
4      scooter          422.0            0.0  04/14/2019 12:15:00 AM

                 End Time           Modified Date  Month  Hour  Day of Week  \
0                     NaN  12/13/2018 03:36:12 PM    NaN   NaN          NaN
1  04/12/2019 12:00:00 PM  12/21/2018 12:41:42 AM   11.0  11.0          5.0
2  10/07/2018 12:45:00 AM  04/17/2019 01:40:51 AM   10.0   0.0          0.0
3  02/17/2019 12:45:00 AM  04/17/2019 02:43:27 AM    2.0   0.0          0.0
4  04/14/2019 12:15:00 AM  04/17/2019 01:47:45 AM    4.0   0.0          0.0

   Council District (Start)  Council District (End)    Year  \
0                       0.0                     0.0     NaN
1                       9.0                     0.0  2018.0
2                       9.0                     9.0  2018.0
3                       9.0                     9.0  2019.0
4                       9.0                     9.0  2019.0

  Census Tract Start Census Tract End
0                NaN              NaN
1                NaN              NaN
2        48453001100      48453001100
3        48453000601      48453000603
4        48453001100      48453001100


The describtion of numerical columns is:
        Trip Duration  Trip Distance         Month          Hour   Day of Week  \
count   4.414974e+06   4.414974e+06  4.414974e+06  4.414974e+06  4.414974e+06
mean    6.818480e+02   3.753060e+04  6.274032e+00  1.460380e+01  3.203368e+00
std     5.907699e+03   8.220604e+06  3.771023e+00  4.676396e+00  2.068076e+00
min    -8.616100e+04  -1.672411e+07  1.000000e+00  0.000000e+00  0.000000e+00
25%     2.290000e+02   4.040000e+02  3.000000e+00  1.200000e+01  1.000000e+00
50%     4.000000e+02   9.400000e+02  6.000000e+00  1.500000e+01  3.000000e+00
75%     7.670000e+02   1.805000e+03  1.000000e+01  1.800000e+01  5.000000e+00
max     1.149160e+07   2.147484e+09  1.200000e+01  2.300000e+01  6.000000e+00

       Council District (Start)  Council District (End)          Year
count              4.413809e+06            4.413809e+06  4.414974e+06
mean               7.728856e+00            7.661869e+00  2.018478e+03
std                2.627749e+00            2.673182e+00  4.995111e-01
min                0.000000e+00            0.000000e+00  2.018000e+03
25%                9.000000e+00            9.000000e+00  2.018000e+03
50%                9.000000e+00            9.000000e+00  2.018000e+03
75%                9.000000e+00            9.000000e+00  2.019000e+03
max                1.000000e+01            1.000000e+01  2.019000e+03

And the describtion of categorial columns is:
                                           ID  \
count                                4414975
unique                               4414975
top     f43b57ff-6112-431c-b616-317c58467102
freq                                       1

                                   Device ID Vehicle Type  \
count                                4414975      4414974
unique                                 43614            2
top     b5025f6a-7238-453d-865d-8cd293159726      scooter
freq                                     604      4225859

                    Start Time                End Time  \
count                  4414974                 4414974
unique                   32619                   32691
top     03/16/2019 04:45:00 PM  03/10/2019 04:45:00 PM
freq                      1441                    1372

                 Modified Date Census Tract Start Census Tract End
count                  4414975            4413807          4413807
unique                    2082                238              252
top     04/17/2019 02:35:02 AM        48453001100      48453001100
freq                     13277            1580987          1531282

***
# Chosen dataset: NYC Turnstile usage data
## There is two csv files (2017 & 2018)

In [7]:
subway_2017 = pd.read_csv('~/Downloads/nys-turnstile-usage-data/turnstile-usage-data-2017.csv')
subway_2018 = pd.read_csv('~/Downloads/nys-turnstile-usage-data/turnstile-usage-data-2018.csv')

preview_data(subway_2017)

The dimension of the table is: (8878203, 11)


First 5 rows preview:
     C/A  Unit       SCP         Station Line Name Division  \
0  R629  R065  00-00-01     ROCKAWAY AV         3      IRT
1  N317  R267  02-06-00           46 ST        MR      IND
2  B025  R150  00-00-00        AVENUE U        BQ      BMT
3  A061  R142  00-00-00  DELANCEY/ESSEX      FJMZ      BMT
4  R257  R182  01-03-00          116 ST         6      IRT

                      Date      Time Description   Entries  \
0  2017-01-06T00:00:00.000  15:00:00     REGULAR   5723234
1  2017-01-04T00:00:00.000  16:00:00     REGULAR    281688
2  2017-01-01T00:00:00.000  20:00:00     REGULAR   4052069
3  2017-01-01T00:00:00.000  16:00:00     REGULAR  10956480
4  2017-01-02T00:00:00.000  00:00:00     REGULAR   8620297

   Exits
0                                            5956815
1                                             388139
2                                            2654916
3                                           10663406
4                                            9569207


The describtion of numerical columns is:
             Entries  \
count  8.878203e+06
mean   3.829531e+07
std    2.037046e+08
min    0.000000e+00
25%    5.061090e+05
50%    2.659916e+06
75%    6.814634e+06
max    2.130669e+09

       Exits
count                                       8.878203e+06
mean                                        3.071709e+07
std                                         1.842514e+08
min                                         0.000000e+00
25%                                         2.508190e+05
50%                                         1.491007e+06
75%                                         4.770183e+06
max                                         2.140537e+09

And the describtion of categorial columns is:
             C/A     Unit       SCP         Station Line Name Division  \
count   8878203  8878203   8878203         8878203   8878203  8878203
unique      737      470       237             380       114        6
top       PTH22     R549  00-00-00  34 ST-PENN STA         1      IRT
freq      65008   125949    872648          188255   1050035  3231017

                           Date      Time Description
count                   8878203   8878203     8878203
unique                      315     84923           2
top     2017-04-12T00:00:00.000  04:00:00     REGULAR
freq                      31452    687627     8845081

In [ ]:
pd.